name: Update Backup Repos

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  update-backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch GitHub Repos and Save to Backup
      run: |
        curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/users/${{ github.repository_owner }}/repos -o ./src/data/backup-repos.json

    - name: Commit and Push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add ./src/data/backup-repos.json
        git commit -m "Update backup-repos.json"
        git push
